### ISSUE TITLE
could you provide a precompiled file

### ISSUE THREAD

**Issue by guest256** [Zeal8bit/Zeal-8-bit-OS#2]
i'm having problems installing the dependencies to compile an iso.

**Comment by marioc8** [comment]
[a.zip](https://github.com/Zeal8bit/Zeal-8-bit-OS/files/9825053/a.zip)

Maybe it will help. Compiled few hours ago.

**Comment by Zeal8bit** [comment]
Hi @guest256 ,

Thanks for the suggestion, you will find a compiled binary for the `v0.1.0` here: https://github.com/Zeal8bit/Zeal-8-bit-OS/releases/tag/v0.1

You will also find the map file which contains all the symbols and the configuration with which the binary was compiled.
