### ISSUE TITLE
`less` command will clear the screen after exit it

### ISSUE THREAD

**Issue by JasonMo1** [Zeal8bit/Zeal-8-bit-OS#25]
less command on linux will not clear the screen, there's a little difference in this behavior.

**Comment by JasonMo1** [comment]
reproduction:

run `less simple.txt` in zos and press q to quit

**Comment by Zeal8bit** [comment]
This is the expected behavior since `less` command erases the screen, it doesn't save the characters shown on screen beforehand (it has no way of doing this anyway)
