### ISSUE TITLE
Can I read from STDIN byte by byte?

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-8-bit-OS#30]
This code read from stdin and return a Forth counted string (len in the first byte). Tested using the emulator, while waiting for my board from Aliexpress.

```
; Parameters:
;   H   - Device to read from.
;   DE  - Buffer to store the line.
;   B   - Size of the buffer passed.
; Returns:
;   A   - ERR_SUCCESS on success, error value else

read_line:
    push h          ; device

    push de       ; buffer
    ld c, 0          ; line len
    ld (de), c      ; store line len.
    inc  de         ; Reserve 1 byte for the len.

    ;   Test for zero length buffer
    ld  a, 0
    cp  b
    jp  z, end

cycle:
    ; Read bytes by polling, one at time
    push bc
    ld  bc, 1    
    READ   
    pop bc 
    
    cp a, ERR_SUCCESS
    jr nz, cycle
br:
    ;   Move char to buffer
    ld  a, (de) ; a <- last char read
    inc de      ; buffer++
    ;   Update count
    inc c       ; used++
     
    ;   Check the ending '\n'   
    cp a, '\n'  
    jr z, end

    ; Check buffer full
    djnz cycle

end:
    pop de
    pop h

    ld a, ERR_SUCCESS
    ld (de), c      ; len of the counted string
    ret    

```

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe !

By default, the standard input (keyboard) works in cooked mode. Just like on Linux, in this mode, the driver will read the input keys and process them, until the user provides presses Enter key. Thus, the given buffer will always be terminated with a `\n` character.

In your program, you can take advantage of this mode to implement your `read_line` routine as follows:

```
; Parameters:
;   H   - Device to read from.
;   DE  - Buffer to store the line.
;   B   - Size of the buffer passed.
; Returns:
;   A   - ERR_SUCCESS on success, error value else

read_line:
    ; Make sure the size is > 1 (we need at least 2 cells to store a char + the size)
    ld a, b
    cp 1
    jr nc, read_line_error
    ; The first byte of the buffer will be used to store the length, do not provide it to the READ syscall
    inc de
    dec b
    ; Prepare the length for the READ syscall
    ld c, b
    ld b, 0
    READ()
    ; Check the error
    or a
    ret nz
    ; The number of bytes written in the buffer was returned in BC, guaranteed to be < 256 since BC was < 256 before calling READ
    ; Write this 8-bit value to the first cell of original DE
    dec de
    ld a, c
    ld (de), a
    ; A = ERR_SUCCESS
    xor a
    ret
read_line_error:
    ld a, ERR_INVALID_PARAMETER
    ret
```

If you still want to have full control over the keyboard inputs, you can set the standard input in **raw** mode, thanks to the `ioctl` syscall. In this mode, ALL the keys pressed and released by the user will be filled in the buffer you provide to the `READ` syscall. This means that you will need to interpret all the `KB_RELEASED` events that will occur as well as manage the special keys, you can find the list here: https://github.com/Zeal8bit/Zeal-8-bit-OS/blob/main/include/drivers/keyboard_h.asm

An example of a program using this mode is [Zepto text editor](https://github.com/Zeal8bit/Zepto/), as you can see here: https://github.com/Zeal8bit/Zepto/tree/main/src#L206 and here https://github.com/Zeal8bit/Zepto/tree/main/src#L231

**Comment by Candid-Moe** [comment]
Hi.

I tried to Buy the board on Aliexpress, but my  order was canceled due to
seller times out.
Where else can I buy the Zeal 8 bit?

Thanks

Andrés

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe ,

Can you please contact me by mail: contact [at] zeal8bit.com

Or on Discord if you already joined it?

**Comment by Candid-Moe** [comment]
Here I'm.

Please, use ***@***.*** This Gmail account is only for one-time
contacts.

Love your work, bro.

Andrés
