### ISSUE TITLE
How to add a program to the filesystem?

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-8-bit-OS#31]
I use "load nnn" to load a program via UART and run it. No problem.

How do I do to have that program stored permanently in the file system, like init.bin?

It's a user program, not a bootable one.

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe ,

Sorry for the late reply! When building the OS, the `romdisk` is also getting build, what you can do is specify the files that you want to include inside the romdisk thanks to the environment variable `EXTRA_ROMDISK_FILES`, for example:
```
$ cat /home/path/to/your/files/hello.txt
This is a new file! I need to be part of the romdisk
$ cat /home/path/to/your/files/file.txt
This is another file...
$ cd /path/to/Zeal-8-bit-OS
$ export EXTRA_ROMDISK_FILES="/home/path/to/your/files/hello.txt /home/path/to/your/files/file.txt"
$ make
...
Packing the files
pack disk.img build/init.bin simple.txt /home/path/to/your/files/hello.txt /home/path/to/your/files/file.txt
...
```
The files will then be part of the romdisk!

If it's for development with the emulator (https://github.com/Zeal8bit/Zeal-WebEmulator), I just pushed (few minutes ago) a new commit that adds support for a `HostFS`, thanks to that, you will be able to mount a directory of your host computer inside Zeal 8-bit OS, which will be disk `H:/`.

**Comment by Candid-Moe** [comment]
Due to keyboard situation, I have no way to enter a colon.

**Comment by Candid-Moe** [comment]
I'm late. Sorry
I tried the option. After asking for a directory, it hung up. The directory only has two files, less than 20 KB.
![Screenshot at 2024-07-14 16-02-28](https://github.com/user-attachments/assets/9e6edc87-bfeb-4be5-90f6-793b59ca8f51)

**Comment by Zeal8bit** [comment]
@Candid-Moe you want to cd to the disk first:
```
cd h:/
```
then you can `ls`

**Comment by Candid-Moe** [comment]
That works! Thanks you

**Comment by Candid-Moe** [comment]
Closed
