### ISSUE TITLE
make failed  errors_h.asm:1: error: syntax error

### ISSUE THREAD

**Issue by buffge** [Zeal8bit/Zeal-8-bit-OS#4]
env: 
- ubuntu 20.04
- z88dk snap edge
- z88dk-z80asm  Z80 Macro Assembler 20302-71a8b6787-20221110

make output:
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
ls.asm:73: error: undefined symbol: ERR_NO_MORE_ENTRIES
  ^---- ERR_NO_MORE_ENTRIES
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
errors_h.asm:1: error: syntax error
  ^---- ../../../include/errors_h.asm
errors.asm:10: error: undefined symbol: ERR_NO_MORE_ENTRIES
  ^---- ERR_NO_MORE_ENTRIES
errors.asm:105: error: undefined symbol: ERR_FAILURE
  ^---- ERR_FAILURE
make[1]: *** [Makefile:13: all] Error 1
make[1]: Leaving directory '/home/buff/projects/asm/Zeal-8-bit-OS/target/zeal8bit/romdisk'
make: *** [Makefile:106: precmd] Error 2

l think Micro is not support, but l aleardy use the last version z88dk

**Comment by Zeal8bit** [comment]
Hi @buffge ,

That's odd, there is no macro in that file. the assembler seems to be unhappy about the first line of `errors_h.asm`, which is a comment:
```
; SPDX-FileCopyrightText: 2022 Zeal 8-bit Computer <contact@zeal8bit.com>
```

However, the file `errors_h.asm` in `romdisk` directory is a symbolic link to the `include/error_h.asm` file. Can you check if your link is not broken? You should get something like this:
```
$ ls -l target/zeal8bit/romdisk/errors_h.asm
lrwxrwxrwx 1 zeal zeal 29 Aug 11 14:42 target/zeal8bit/romdisk/errors_h.asm -> ../../../include/errors_h.asm
```
and
```
$ cat target/zeal8bit/romdisk/errors_h.asm
; SPDX-FileCopyrightText: 2022 Zeal 8-bit Computer <contact@zeal8bit.com>
;
; SPDX-License-Identifier: Apache-2.0

        IFNDEF ERRORS_H
        DEFINE ERRORS_H
[...]
``` 

If you can't see the file content after `cat`, then you may have moved the original `errors_h.asm` file which should be in `include`.
Have you modified anything in the repo?

**Comment by buffge** [comment]
Thank you for your answer. It's really a link problem, because l have clone to local pc and dev at local clion, clion sync the file to server, this leads to link failure. it's my fault,I should check it carefully

**Comment by Zeal8bit** [comment]
@buffge Ah yes, links and permissions may be fragile in environments involving cloud/remote storage (Dropbox, Google Drive, etc...)

Anyways, this file was not meant to stay forever, it was a workaround before I provide official public headers. The kernel headers are now online so I just updated `romdisk` source files, in commit [9a2ddd0](https://github.com/Zeal8bit/Zeal-8-bit-OS/commit/9a2ddd02e64328740b073df4ef518947c1327ad8), to use them, instead of having a link to `errors_h.asm`, which has been deleted.
