### ISSUE TITLE
RTC works in emulation, fails in real hardware

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-8-bit-OS#41]
I wrote this little Forth word that execute a SYSCALL 22 to get current time and date.

```
8 buffer: sys-date
: date ( -- )
    22 sys-date 0 0  ( HL DE BC A registers pushed into the stack )
    z80-syscall         ( do the syscall and put the registers in the stack HL DE BC A )
    ." Return code " . cr
    ." Date " sys-date 8 dump cr
    ;
```
The word works fine in emulation:

![Screenshot at 2024-11-05 16-18-35](https://github.com/user-attachments/assets/8a0a95e5-fc9d-4468-97e4-8126ef694cf8)

But in the real Zeal 8-bit board, it doesn't work:

![Screenshot at 2024-11-05 16-21-24](https://github.com/user-attachments/assets/4bc17c5e-c5bd-4378-a6f5-5742c0f966ef)

The board has a CR2032 battery installed for the RTC (is that necessary) . The voltage is 2.97 v 

The boot screen doesn't show an active timer:

![Screenshot at 2024-11-05 15-57-23](https://github.com/user-attachments/assets/f5e3f43e-da45-4ca1-b470-1cd7e5301168)

**How to test**

You can test in emulation using https://github.com/Candid-Moe/Zorth/blob/main/prod/zorth.bin

For test in real hardware, use https://github.com/Candid-Moe/Zorth/blob/main/prod/os_with_romdisk.img

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe !

What you did is correct, I suspect the RTC is stopped in your case. When you put in a CR battery, the RTC won't start automatically, it needs to be setup.
The bit `7` of its register `00`  needs to be cleared. This needs to be done every time the RTC battery runs out. The `getdate` syscall doesn't show this register 0's bit 7.

You have two solutions here, from easiest to hardest:
* Use the `Test hardware` option in the bootloader, which will clear this bit in the RTC automatically. (It will show `Disabled (no battery?)` but will enable it right after)
* Set the date via the `date` command on Zeal 8-bit OS command prompt. 
* Write an I2C routine in your program that clears bit 7 of register 0

**Comment by Candid-Moe** [comment]
The "Test Hardware" fixed the problem. Now the clock is ticking but I can't change the date&time. Working on it.
